package projetcrypto;

import javax.swing.JPanel;

public class InterfacePrincipale extends javax.swing.JFrame {
    private Carte jeuDeCarte[];
    private char lettres[];
    private char clefDeBase[];
    private char clefCourante[];
    
    public InterfacePrincipale() {
        initComponents();
        this.jeuDeCarte = new Carte[54];
    }
    
    private void affGraphCarte(JPanel jp, int[] tabCarte){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CentreMod = new javax.swing.JPanel();
        i_head = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        randClef = new javax.swing.JButton();
        defClef = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        i_foot = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        decMess = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        decMessSous = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        decMessFinal = new javax.swing.JLabel();
        i_body = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        clefC = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        messCrypt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        crypter = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        messageCrpt = new javax.swing.JLabel();
        AffichageGeneral = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        CentreMod.setLayout(new java.awt.BorderLayout());

        i_head.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.GridLayout(1, 2));

        randClef.setText("Aléatoire");
        randClef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randClefActionPerformed(evt);
            }
        });
        jPanel5.add(randClef);

        defClef.setText("Définir");
        defClef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defClefActionPerformed(evt);
            }
        });
        jPanel5.add(defClef);

        i_head.add(jPanel5, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Ordre initial des cartes :");
        i_head.add(jLabel1, java.awt.BorderLayout.NORTH);

        CentreMod.add(i_head, java.awt.BorderLayout.PAGE_START);

        i_foot.setLayout(new java.awt.BorderLayout());

        jButton3.setText("Décrypter");
        i_foot.add(jButton3, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.GridLayout(6, 0));

        jLabel3.setText("Message crypté :");
        jPanel2.add(jLabel3);
        jPanel2.add(decMess);

        jLabel8.setText("Soustraction :");
        jPanel2.add(jLabel8);
        jPanel2.add(decMessSous);

        jLabel10.setText("Message :");
        jPanel2.add(jLabel10);
        jPanel2.add(decMessFinal);

        i_foot.add(jPanel2, java.awt.BorderLayout.CENTER);

        CentreMod.add(i_foot, java.awt.BorderLayout.PAGE_END);

        i_body.setLayout(new java.awt.GridLayout(9, 1));

        jLabel4.setText("Ordre courant des cartes :");
        i_body.add(jLabel4);

        jPanel1.setLayout(new java.awt.GridLayout());
        jScrollPane1.setViewportView(jPanel1);

        i_body.add(jScrollPane1);

        jLabel5.setText("Clef courante :");
        i_body.add(jLabel5);
        i_body.add(clefC);

        jLabel6.setText("Message à crypter : ");
        i_body.add(jLabel6);
        i_body.add(messCrypt);

        jPanel3.setLayout(new java.awt.GridLayout());

        crypter.setText("Cryptage directe");
        jPanel3.add(crypter);

        jButton1.setText("Cryptage manuel");
        jPanel3.add(jButton1);

        i_body.add(jPanel3);

        jLabel2.setText("Message crypté :");
        i_body.add(jLabel2);
        i_body.add(messageCrpt);

        CentreMod.add(i_body, java.awt.BorderLayout.CENTER);

        getContentPane().add(CentreMod);

        AffichageGeneral.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(AffichageGeneral);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void randClefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randClefActionPerformed
        this.jeuDeCarte = new Carte[54];
        int val[] = new int[54];
        for(int i = 0; i < 54; i++)
            val[i] = i + 1;
        int k = 0;
        while(k != 54){
            int rnd = (int) (Math.random() * 54) + 1;
            if(val[rnd - 1] != 0){
                this.jeuDeCarte[k] = new Carte(rnd);
                System.out.println("indice :" + rnd + " getElement : " + jeuDeCarte[k].getElement());
                k++;
                val[rnd - 1] = 0;
            }
        }
        ///Affichage General
    }//GEN-LAST:event_randClefActionPerformed

    private void defClefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defClefActionPerformed
        InterfaceGenerClef igc = new InterfaceGenerClef(this,false);
        this.setVisible(false);
        igc.setVisible(true);
        igc.setLocationRelativeTo(null);
    }//GEN-LAST:event_defClefActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfacePrincipale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AffichageGeneral;
    private javax.swing.JPanel CentreMod;
    private javax.swing.JLabel clefC;
    private javax.swing.JButton crypter;
    private javax.swing.JLabel decMess;
    private javax.swing.JLabel decMessFinal;
    private javax.swing.JLabel decMessSous;
    private javax.swing.JButton defClef;
    private javax.swing.JPanel i_body;
    private javax.swing.JPanel i_foot;
    private javax.swing.JPanel i_head;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField messCrypt;
    private javax.swing.JLabel messageCrpt;
    private javax.swing.JButton randClef;
    // End of variables declaration//GEN-END:variables
}
